services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db:
